
[build-system]
requires = ["setuptools>=65.3.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dicomfix"
version = "0.1.0"
description = "A brief description of what your project does"
authors = [{name = "Niels Bassler", email = "nbassler@users.noreply.github.com"}]
license-expression = "MIT"
readme = "README.md"
dependencies = [
    "pydicom>=2.3.1"
]
packages = [
    {include = "dicomfix"},
]

[project.optional-dependencies]
dev = [
    "flake8>=3.8.0",
    "pytest>=6.0.0"
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(message)s"

log_file = "pytest.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"

[tool.flake8]
max-line-length = 120

[tool.yapf]
based_on_style = "pep8"
column_limit = 120
